
name: myDartWorkflow

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install dependencies
        run: flutter pub get

      - name: Build project in debug mode
        run: flutter build apk --debug

      - name: List all files
        run: ls -all